#!/usr/bin/env sh

#SKHD STUFF

# if you're having troubles finding key codes for a key just type skhd --observe in a terminal and type a key. Pretty cool! Or just check the wiki.

## HYPER == SHIFT + CMD + ALT + OPTION

## Open Terminal
hyper - t : open -na /System/Applications/Utilities/Terminal.app

## Open Launchpad
hyper - l : open -na /System/Applications/Launchpad.app

## Open Mission Control
hyper - m : open -na /System/Applications/'Mission Control.app'

## Open new Finder window
hyper - f : open -na Finder

## Maximize window size
hyper - 1 : yabai -m window --toggle zoom-fullscreen
