#!/usr/bin/env sh

#SKHD STUFF

## HYPER == SHIFT + CMD + ALT + OPTION


# ===== Launching stuff ===============
## Master workflow for work
hyper - enter : {
  exec : "open -a '/Applications/Microsoft Teams.app' && open -a '/Applications/Microsoft Outlook.app'"
}
## Open iTerm2
hyper - t : open -a "/Applications/iTerm.app"
## Open Launchpad
hyper - l : open "/System/Applications/Launchpad.app"
## Open Mission Control
hyper - m : open "/System/Applications/Mission Control.app"
## Open new Finder window
hyper - f : open -R "$HOME/Documents"


# ===== Yabai =========================
## Maximize window size
lalt - f : yabai -m window --toggle zoom-fullscreen

# Float / Unfloat window: lalt - space
lalt - space : yabai -m window --toggle float

# Space Navigation (four spaces per display): lalt - {1, 2, 3, 4}
lalt - 1 : SPACES=($(yabai -m query --displays --display | jq '.spaces[]')) && [[ -n $SPACES[1] ]] && yabai -m space --focus $SPACES[1]
lalt - 2 : SPACES=($(yabai -m query --displays --display | jq '.spaces[]')) && [[ -n $SPACES[2] ]] && yabai -m space --focus $SPACES[2]
lalt - 3 : SPACES=($(yabai -m query --displays --display | jq '.spaces[]')) && [[ -n $SPACES[3] ]] && yabai -m space --focus $SPACES[3]
lalt - 4 : SPACES=($(yabai -m query --displays --display | jq '.spaces[]')) && [[ -n $SPACES[4] ]] && yabai -m space --focus $SPACES[4]

# Window Navigation (through display borders): lalt - {j, k, l, ö}
lalt - j    : yabai -m window --focus west  || yabai -m display --focus west
lalt - k    : yabai -m window --focus south || yabai -m display --focus south
lalt - l    : yabai -m window --focus north || yabai -m display --focus north
lalt - 0x29 : yabai -m window --focus east  || yabai -m display --focus east

# Moving windows between spaces: shift + lalt - {1, 2, 3, 4, p, n } (Assumes 4 Spaces Max per Display)
shift + lalt - 1 : SPACES=($(yabai -m query --displays --display | jq '.spaces[]')) && [[ -n $SPACES[1] ]] \
                  && yabai -m window --space $SPACES[1]

shift + lalt - 2 : SPACES=($(yabai -m query --displays --display | jq '.spaces[]')) && [[ -n $SPACES[2] ]] \
                  && yabai -m window --space $SPACES[2]

shift + lalt - 3 : SPACES=($(yabai -m query --displays --display | jq '.spaces[]')) && [[ -n $SPACES[3] ]] \
                  && yabai -m window --space $SPACES[3]

shift + lalt - 4 : SPACES=($(yabai -m query --displays --display | jq '.spaces[]')) && [[ -n $SPACES[4] ]] \
                  && yabai -m window --space $SPACES[4]

# Rotate on X and Y Axis
shift + lalt - x : yabai -m space --mirror x-axis
shift + lalt - y : yabai -m space --mirror y-axis

# Equalize size of windows: ctrl + lalt - e
ctrl + lalt - e : yabai -m space --balance

# Sketchybar stuff
#lalt - space : yabai -m window --toggle float; sketchybar --trigger window_focus
#shift + lalt - f : yabai -m window --toggle zoom-fullscreen; sketchybar --trigger window_focus
#lalt - f : yabai -m window --toggle zoom-parent; sketchybar --trigger window_focus
