#!/usr/bin/env sh
#YABAI STUFF


# ===== Loading Scripting Additions ============

# Unload the macOS WindowManager process
#launchctl unload -F /System/Library/LaunchAgents/com.apple.WindowManager.plist > /dev/null 2>&1 &

# See: https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#macos-big-sur---automatically-load-scripting-addition-on-startup
sudo yabai --load-sa
#yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
#yabai -m signal --add event=display_added action="sleep 2 && $HOME/.dotfiles/yabai/create_spaces.sh"
#yabai -m signal --add event=display_removed action="sleep 1 && $HOME/.dotfiles/yabai/create_spaces.sh"
#$HOME/.dotfiles/yabai/create_spaces.sh

# Move space 1, aka comms, to the second display when it's connected
#yabai -m space 1 --display 2
#yabai -m display --add 2 --space 1


# ===== Tiling setting =========================

## bsp or float (default: bsp)
yabai -m config layout bsp

## window things
yabai -m config top_padding 5 \
         config bottom_padding 5 \
         config left_padding 5 \
         config right_padding 5 \
         config window_gap 10 \
         config auto_balance off \
         config split_ratio 0.50 \
         config window_placement second_child \
         config window_topmost off \
         config window_shadow float \
         config window_opacity off \
         config window_border off

## mouse things
yabai -m config focus_follows_mouse on \
         mouse_modifier alt \
         mouse_action1 move \
         mouse_action2 resize \
         mouse_drop_action stack 


# ===== Rules ==================================

## these are apps I just don't want managed by yabai
yabai -m rule --add app="^(Software Update|Calculator|Software Update|Dictionary|VLC|System Preferences|System Settings|Photo Booth|Archive Utility|App Store|Steam|Activity Monitor|zoom.us)$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^Disk Utility$" manage=off
yabai -m rule --add app="^System Information$" manage=off
yabai -m rule --add app="^Path Finder$" manage=off
yabai -m rule --add app="^TextEdit$" manage=off
yabai -m rule --add app="^GitHub Desktop$" manage=off
yabai -m rule --add app="^Messages$" manage=off
yabai -m rule --add app="^Windows App$" manage=off
yabai -m rule --add label="Select file to save to" app="^Inkscape$" title="Select file to save to" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off

## these are apps I want to launch to specific displays and spaces
yabai -m rule --add app="Outlook" space=^1
yabai -m rule --add app="Teams" space=^1
yabai -m rule --add app="Code" space=^2
yabai -m rule --add app="Chrome" space=^3
yabai -m rule --add app="iTerm" space=^4
yabai -m rule --add app="Termius" space=^4


#END

